# [START appengine_websockets_yaml]
runtime: nodejs18
env: standard
instance_class: F1
service: default

# Use only a single instance, so that this local-memory-only chat app will work
# consistently with multiple users. To work across multiple instances, an
# extra-instance messaging system or data store would be needed.

network:
  session_affinity: true

# env_variables:
#   NEXT_PUBLIC_API_URL: "http://34.93.107.165/"
#   NEXT_PUBLIC_PORT: "myport"


# network:
#   session_affinity: true
# [END appengine_websockets_yaml]

